# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuits',
            fields=[
                ('circuitid', models.AutoField(primary_key=True, serialize=False)),
                ('circuitref', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('alt', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'circuits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructorResults',
            fields=[
                ('constructorresultsid', models.AutoField(primary_key=True, serialize=False)),
                ('raceid', models.IntegerField()),
                ('constructorid', models.IntegerField()),
                ('points', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'constructor_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Constructors',
            fields=[
                ('constructorid', models.AutoField(primary_key=True, serialize=False)),
                ('constructorref', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'constructors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructorStandings',
            fields=[
                ('constructorstandingsid', models.AutoField(primary_key=True, serialize=False)),
                ('raceid', models.IntegerField()),
                ('constructorid', models.IntegerField()),
                ('points', models.FloatField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(blank=True, max_length=255, null=True)),
                ('wins', models.IntegerField()),
            ],
            options={
                'db_table': 'constructor_standings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driverid', models.AutoField(primary_key=True, serialize=False)),
                ('driverref', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('forename', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverStandings',
            fields=[
                ('driverstandingsid', models.AutoField(primary_key=True, serialize=False)),
                ('raceid', models.IntegerField()),
                ('driverid', models.IntegerField()),
                ('points', models.FloatField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(blank=True, max_length=255, null=True)),
                ('wins', models.IntegerField()),
            ],
            options={
                'db_table': 'driver_standings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LapTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceid', models.IntegerField()),
                ('driverid', models.IntegerField()),
                ('lap', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lap_times',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PitStops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceid', models.IntegerField()),
                ('driverid', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('lap', models.IntegerField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pit_stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('qualifyid', models.AutoField(primary_key=True, serialize=False)),
                ('raceid', models.IntegerField()),
                ('driverid', models.IntegerField()),
                ('constructorid', models.IntegerField()),
                ('number', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('q1', models.CharField(blank=True, max_length=255, null=True)),
                ('q2', models.CharField(blank=True, max_length=255, null=True)),
                ('q3', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'qualifying',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('raceid', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('circuitid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'races',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('resultid', models.AutoField(primary_key=True, serialize=False)),
                ('raceid', models.IntegerField()),
                ('driverid', models.IntegerField()),
                ('constructorid', models.IntegerField()),
                ('number', models.IntegerField(blank=True, null=True)),
                ('grid', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(blank=True, max_length=255, null=True)),
                ('positionorder', models.IntegerField()),
                ('points', models.FloatField()),
                ('laps', models.IntegerField()),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('fastestlap', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('fastestlaptime', models.CharField(blank=True, max_length=255, null=True)),
                ('fastestlapspeed', models.CharField(blank=True, max_length=255, null=True)),
                ('statusid', models.IntegerField()),
            ],
            options={
                'db_table': 'results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'seasons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
    ]
